In [1]:
import numpy as np
from sonnmf.expanded import non_neg

W = np.random.uniform(-1, 1, (5, 5))
nnW = non_neg(W)

In [2]:
np.maximum(0, W) == nnW

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [3]:
from sonnmf.expanded import calculate_fscore as cf1
from sonnmf.gpt import calculate_fscore as cf2

m, n, r = 50, 30, 8
M = np.random.random((m, n))
W = np.random.random((m, r))
H = np.random.random((r, n))

cf1(M, W, H) == cf2(M, W, H)

True

In [4]:
from sonnmf.expanded import calculate_gscore as cg1
from sonnmf.gpt import calculate_gscore as cg2

# W = np.random.uniform(-1, 1, (m, r))
cg1(W) == cg2(W)

True

In [5]:
from sonnmf.expanded import calculate_hscore as ch1
from sonnmf.gpt import calculate_hscore as ch2


ch1(W) == ch2(W)

True

In [6]:
from sonnmf.expanded import prox as p1
from sonnmf.gpt import prox as p2


p1(0.3, W[:, 0:1], W[:, 1:2]) == p2(0.3, W[:, 0:1], W[:, 1:2])

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [7]:
from sonnmf.expanded import proj_simplex as ps1
from sonnmf.gpt import proj_simplex as ps2

ps1(W[:, 0:1]) == ps2(W[:, 0:1])

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [8]:
from sonnmf.expanded import sonnmf_with_penalty as nmf1
from sonnmf.gpt import nmf_with_penalty as nmf2

nmf1(M, W.copy(), H.copy(), lam=1, gamma=1, itermax=10, verbose=True)

Iteration: 0, f=2370.9694599731924, g=82.08921944716482, h=-0.0, total=2453.0586794203573
Iteration: 1, f=53.34801704900569, g=52.644953835090014, h=0.3022581941562811, total=106.29522907825199
Iteration: 2, f=49.81064452184289, g=48.732027539331106, h=-0.0, total=98.54267206117399
Iteration: 3, f=49.400076241876796, g=48.441266329794416, h=-0.0, total=97.84134257167122
Iteration: 4, f=49.23545507371127, g=48.19736148482824, h=-0.0, total=97.43281655853951
Iteration: 5, f=49.01607133030621, g=48.52460816818055, h=-0.0, total=97.54067949848675
Iteration: 6, f=48.74557643395514, g=49.203211704501946, h=-0.0, total=97.94878813845708
Iteration: 7, f=48.456109638307026, g=49.98954198922649, h=-0.0, total=98.44565162753352
Iteration: 8, f=48.16322482535343, g=50.776993445650795, h=-0.0, total=98.94021827100423
Iteration: 9, f=47.884997794778066, g=51.52212884496981, h=-0.0, total=99.40712663974787
Iteration: 10, f=47.61174401393513, g=52.226282053724944, h=-0.0, total=99.83802606766008


(array([[0.50817136, 0.62098817, 0.42835105, 0.59181622, 0.23697881,
         0.4734388 , 0.76342664, 0.47679554],
        [0.76126901, 0.27930762, 0.45435601, 0.60380263, 0.87435967,
         0.68045969, 0.7157782 , 0.37062226],
        [0.48334834, 0.36566701, 0.62999865, 0.67950962, 0.36090696,
         0.53726801, 0.55834371, 0.52913385],
        [0.46214402, 0.16868089, 0.68028998, 0.52170954, 0.56258982,
         0.39867458, 0.87676967, 0.56135633],
        [0.36835301, 0.58915432, 0.46299212, 0.52992642, 0.60638354,
         0.1922481 , 0.35376773, 0.60836405],
        [0.40309579, 0.55186515, 0.14816027, 0.39853681, 0.60866288,
         0.54226121, 0.50334052, 0.25198198],
        [0.36570078, 0.34193493, 0.67121164, 0.43509714, 0.40788557,
         0.21673859, 0.3580731 , 0.61974842],
        [0.47772581, 0.26133509, 0.64412483, 0.43799961, 0.34373196,
         0.16613198, 0.77213401, 0.6341615 ],
        [0.31951035, 0.31275199, 0.62028884, 0.51404008, 0.55458153,
         0.

In [9]:
nmf2(M, W.copy(), H.copy(), lam=1, gamma=1, itermax=10, verbose=True)

Iteration: 0, f=2370.9694599731924, g=82.08921944716482, h=-0.0, total=2453.0586794203573
Iteration: 1, f=53.34801704900569, g=52.644953835090014, h=0.30225819415628113, total=106.29522907825199
Iteration: 2, f=49.81064452184289, g=48.732027539331106, h=-0.0, total=98.54267206117399
Iteration: 3, f=49.400076241876796, g=48.441266329794416, h=-0.0, total=97.84134257167122
Iteration: 4, f=49.23545507371127, g=48.19736148482824, h=-0.0, total=97.43281655853951
Iteration: 5, f=49.01607133030621, g=48.52460816818055, h=-0.0, total=97.54067949848675
Iteration: 6, f=48.74557643395514, g=49.203211704501946, h=-0.0, total=97.94878813845708
Iteration: 7, f=48.456109638307026, g=49.98954198922649, h=-0.0, total=98.44565162753352
Iteration: 8, f=48.16322482535343, g=50.776993445650795, h=-0.0, total=98.94021827100423
Iteration: 9, f=47.884997794778066, g=51.52212884496981, h=-0.0, total=99.40712663974787
Iteration: 10, f=47.61174401393513, g=52.226282053724944, h=-0.0, total=99.83802606766008


(array([[0.50817136, 0.62098817, 0.42835105, 0.59181622, 0.23697881,
         0.4734388 , 0.76342664, 0.47679554],
        [0.76126901, 0.27930762, 0.45435601, 0.60380263, 0.87435967,
         0.68045969, 0.7157782 , 0.37062226],
        [0.48334834, 0.36566701, 0.62999865, 0.67950962, 0.36090696,
         0.53726801, 0.55834371, 0.52913385],
        [0.46214402, 0.16868089, 0.68028998, 0.52170954, 0.56258982,
         0.39867458, 0.87676967, 0.56135633],
        [0.36835301, 0.58915432, 0.46299212, 0.52992642, 0.60638354,
         0.1922481 , 0.35376773, 0.60836405],
        [0.40309579, 0.55186515, 0.14816027, 0.39853681, 0.60866288,
         0.54226121, 0.50334052, 0.25198198],
        [0.36570078, 0.34193493, 0.67121164, 0.43509714, 0.40788557,
         0.21673859, 0.3580731 , 0.61974842],
        [0.47772581, 0.26133509, 0.64412483, 0.43799961, 0.34373196,
         0.16613198, 0.77213401, 0.6341615 ],
        [0.31951035, 0.31275199, 0.62028884, 0.51404008, 0.55458153,
         0.

In [10]:
np.sum(np.linalg.norm(np.diff(W, n=1, axis=1), axis=0))

20.185052096905874

In [11]:
np.diff(W, axis=1)

array([[-0.00377396, -0.20555699, -0.56284978,  0.4124628 , -0.21109292,
         0.42954262, -0.60690446],
       [ 0.40649711,  0.06289389,  0.20692225, -0.78924571, -0.02159897,
         0.52256619,  0.0697485 ],
       [ 0.67340953, -0.01841581, -0.82194037,  0.3664434 ,  0.19538227,
         0.21218504, -0.78698194],
       [-0.05592357, -0.24008777,  0.29508308,  0.05267729, -0.28976048,
        -0.17554294,  0.61106756],
       [-0.19821014,  0.37086133, -0.78262868,  0.21352308,  0.72057532,
        -0.65182769, -0.27194822],
       [ 0.28316309,  0.09163403, -0.21829427, -0.36127008,  0.129448  ,
        -0.30080085,  0.56471747],
       [-0.42381651,  0.25795722, -0.30083783,  0.57260182, -0.82507175,
         0.1000615 ,  0.13852891],
       [ 0.06350325, -0.56819707,  0.37438685,  0.32620452,  0.04184247,
        -0.36276396, -0.00313526],
       [-0.18878968, -0.13419914,  0.9574564 , -0.6548188 , -0.01915489,
         0.57597852, -0.87643734],
       [-0.14311715, -0.5633

In [12]:
W

array([[0.93147153, 0.92769757, 0.72214058, 0.1592908 , 0.5717536 ,
        0.36066068, 0.7902033 , 0.18329883],
       [0.29281619, 0.6993133 , 0.7622072 , 0.96912945, 0.17988374,
        0.15828477, 0.68085096, 0.75059946],
       [0.19550997, 0.8689195 , 0.85050369, 0.02856331, 0.39500672,
        0.59038899, 0.80257402, 0.01559209],
       [0.76274495, 0.70682138, 0.46673361, 0.76181669, 0.81449398,
        0.5247335 , 0.34919056, 0.96025812],
       [0.65069289, 0.45248275, 0.82334408, 0.0407154 , 0.25423848,
        0.97481381, 0.32298612, 0.0510379 ],
       [0.49515081, 0.7783139 , 0.86994793, 0.65165366, 0.29038359,
        0.41983159, 0.11903074, 0.68374821],
       [0.77717827, 0.35336176, 0.61131898, 0.31048115, 0.88308296,
        0.05801121, 0.15807272, 0.29660163],
       [0.57454955, 0.63805281, 0.06985574, 0.44424258, 0.77044711,
        0.81228958, 0.44952562, 0.44639036],
       [0.34134819, 0.15255851, 0.01835937, 0.97581577, 0.32099697,
        0.30184208, 0.877820

In [13]:
norms = np.linalg.norm(W[:, :-1] - W[:, 1:], axis=0)
np.sum(norms)

20.185052096905874

In [14]:
W[:, :-1] - W[:, 1:]

array([[ 0.00377396,  0.20555699,  0.56284978, -0.4124628 ,  0.21109292,
        -0.42954262,  0.60690446],
       [-0.40649711, -0.06289389, -0.20692225,  0.78924571,  0.02159897,
        -0.52256619, -0.0697485 ],
       [-0.67340953,  0.01841581,  0.82194037, -0.3664434 , -0.19538227,
        -0.21218504,  0.78698194],
       [ 0.05592357,  0.24008777, -0.29508308, -0.05267729,  0.28976048,
         0.17554294, -0.61106756],
       [ 0.19821014, -0.37086133,  0.78262868, -0.21352308, -0.72057532,
         0.65182769,  0.27194822],
       [-0.28316309, -0.09163403,  0.21829427,  0.36127008, -0.129448  ,
         0.30080085, -0.56471747],
       [ 0.42381651, -0.25795722,  0.30083783, -0.57260182,  0.82507175,
        -0.1000615 , -0.13852891],
       [-0.06350325,  0.56819707, -0.37438685, -0.32620452, -0.04184247,
         0.36276396,  0.00313526],
       [ 0.18878968,  0.13419914, -0.9574564 ,  0.6548188 ,  0.01915489,
        -0.57597852,  0.87643734],
       [ 0.14311715,  0.5633